version: '3'
networks:
  backend:
services:
  webapp:
    build: ./webapp
    volumes:
      - ./webapp/app:/app
#    ports:
#      - "8080:80"
    networks:
      - backend      
  webapi:
    build: ./web-api
    volumes:
      - ./web-api/app:/app
#    ports:
#      - "8081:80"
    networks:
      - backend      
  frontend:
    image: nginx:1.13
    volumes:
      # Configuração do proxy reverso
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - webapp
      - webapi
    networks:
      - backend        